#!/usr/bin/env bash
# Generate a secure `.env` for Docker Compose (RQG-DOCKER-DEPLOY-001).
# Usage: ./scripts/generate-docker-env.sh [.env path]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/.env}"

if [[ -f "$OUT" ]]; then
  echo "Refusing to overwrite existing file: $OUT" >&2
  echo "Remove it first or pass a different path." >&2
  exit 1
fi

rand() {
  # URL-safe alphanumeric secrets (safe inside DATABASE_URL)
  openssl rand -base64 48 | tr -d '\n/+=' | head -c "${1:-48}"
}

JWT_SECRET="$(rand 48)"
MARKHUB_MASTER_KEY="$(rand 40)"
DEFAULT_ADMIN_PASSWORD="$(rand 24)"
POSTGRES_PASSWORD="$(rand 32)"

cat >"$OUT" <<EOF
# Generated by scripts/generate-docker-env.sh — do not commit
JWT_SECRET=${JWT_SECRET}
MARKHUB_MASTER_KEY=${MARKHUB_MASTER_KEY}
DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
DEFAULT_ADMIN_USERNAME=admin
FORCE_ADMIN_PASSWORD_CHANGE=true
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_USER=markhub
POSTGRES_DB=markhub
EOF

chmod 600 "$OUT"
echo "Wrote ${OUT} (mode 600). Next:"
echo "  docker compose up --build"
echo "  # or Postgres full stack:"
echo "  docker compose --profile postgres-app up --build"
